// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_main module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// corei
//   -> s1n_25
//     -> sm1_26
//       -> rom_ctrl.rom
//     -> sm1_27
//       -> debug_mem
//     -> sm1_28
//       -> ram_main
//     -> sm1_29
//       -> eflash
// cored
//   -> s1n_30
//     -> sm1_26
//       -> rom_ctrl.rom
//     -> sm1_31
//       -> rom_ctrl.regs
//     -> sm1_27
//       -> debug_mem
//     -> sm1_28
//       -> ram_main
//     -> sm1_29
//       -> eflash
//     -> sm1_33
//       -> asf_32
//         -> peri
//     -> sm1_34
//       -> flash_ctrl.core
//     -> sm1_35
//       -> flash_ctrl.prim
//     -> sm1_36
//       -> aes
//     -> sm1_37
//       -> entropy_src
//     -> sm1_38
//       -> csrng
//     -> sm1_39
//       -> edn0
//     -> sm1_40
//       -> edn1
//     -> sm1_41
//       -> hmac
//     -> sm1_42
//       -> rv_plic
//     -> sm1_43
//       -> otbn
//     -> sm1_44
//       -> keymgr
//     -> sm1_45
//       -> kmac
//     -> sm1_46
//       -> sram_ctrl_main
//     -> sm1_47
//       -> bus_ctrl
//     -> sm1_48
//       -> untrusted_s
// dm_sba
//   -> s1n_49
//     -> sm1_26
//       -> rom_ctrl.rom
//     -> sm1_31
//       -> rom_ctrl.regs
//     -> sm1_28
//       -> ram_main
//     -> sm1_29
//       -> eflash
//     -> sm1_33
//       -> asf_32
//         -> peri
//     -> sm1_34
//       -> flash_ctrl.core
//     -> sm1_35
//       -> flash_ctrl.prim
//     -> sm1_36
//       -> aes
//     -> sm1_37
//       -> entropy_src
//     -> sm1_38
//       -> csrng
//     -> sm1_39
//       -> edn0
//     -> sm1_40
//       -> edn1
//     -> sm1_41
//       -> hmac
//     -> sm1_42
//       -> rv_plic
//     -> sm1_43
//       -> otbn
//     -> sm1_44
//       -> keymgr
//     -> sm1_45
//       -> kmac
//     -> sm1_46
//       -> sram_ctrl_main
//     -> sm1_47
//       -> bus_ctrl
//     -> sm1_48
//       -> untrusted_s
// untrusted_m
//   -> s1n_50
//     -> sm1_28
//       -> ram_main
//     -> sm1_29
//       -> eflash
//     -> sm1_33
//       -> asf_32
//         -> peri
//     -> sm1_34
//       -> flash_ctrl.core
//     -> sm1_35
//       -> flash_ctrl.prim
//     -> sm1_36
//       -> aes
//     -> sm1_37
//       -> entropy_src
//     -> sm1_38
//       -> csrng
//     -> sm1_39
//       -> edn0
//     -> sm1_40
//       -> edn1
//     -> sm1_41
//       -> hmac
//     -> sm1_42
//       -> rv_plic
//     -> sm1_43
//       -> otbn
//     -> sm1_44
//       -> keymgr
//     -> sm1_45
//       -> kmac
//     -> sm1_46
//       -> sram_ctrl_main

module xbar_main (
  input clk_main_i,
  input clk_fixed_i,
  input rst_main_ni,
  input rst_fixed_ni,
  input   bus_ctrl_pkg::master_bits_t master_bits_i,
  input   bus_ctrl_pkg::slave_bits_t  slave_bits_i,
  output  logic                       master_bit_peri_secure_en_o,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_corei_i,
  output tlul_pkg::tl_d2h_t tl_corei_o,
  input  tlul_pkg::tl_h2d_t tl_cored_i,
  output tlul_pkg::tl_d2h_t tl_cored_o,
  input  tlul_pkg::tl_h2d_t tl_dm_sba_i,
  output tlul_pkg::tl_d2h_t tl_dm_sba_o,
  input  tlul_pkg::tl_h2d_t tl_untrusted_m_i,
  output tlul_pkg::tl_d2h_t tl_untrusted_m_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_rom_ctrl__rom_o,
  input  tlul_pkg::tl_d2h_t tl_rom_ctrl__rom_i,
  output tlul_pkg::tl_h2d_t tl_rom_ctrl__regs_o,
  input  tlul_pkg::tl_d2h_t tl_rom_ctrl__regs_i,
  output tlul_pkg::tl_h2d_t tl_debug_mem_o,
  input  tlul_pkg::tl_d2h_t tl_debug_mem_i,
  output tlul_pkg::tl_h2d_t tl_ram_main_o,
  input  tlul_pkg::tl_d2h_t tl_ram_main_i,
  output tlul_pkg::tl_h2d_t tl_eflash_o,
  input  tlul_pkg::tl_d2h_t tl_eflash_i,
  output tlul_pkg::tl_h2d_t tl_peri_secure_o,
  input  tlul_pkg::tl_d2h_t tl_peri_secure_i,
  output tlul_pkg::tl_h2d_t tl_peri_untrusted_o,
  input  tlul_pkg::tl_d2h_t tl_peri_untrusted_i,
  output tlul_pkg::tl_h2d_t tl_flash_ctrl__core_o,
  input  tlul_pkg::tl_d2h_t tl_flash_ctrl__core_i,
  output tlul_pkg::tl_h2d_t tl_flash_ctrl__prim_o,
  input  tlul_pkg::tl_d2h_t tl_flash_ctrl__prim_i,
  output tlul_pkg::tl_h2d_t tl_hmac_o,
  input  tlul_pkg::tl_d2h_t tl_hmac_i,
  output tlul_pkg::tl_h2d_t tl_kmac_o,
  input  tlul_pkg::tl_d2h_t tl_kmac_i,
  output tlul_pkg::tl_h2d_t tl_aes_o,
  input  tlul_pkg::tl_d2h_t tl_aes_i,
  output tlul_pkg::tl_h2d_t tl_entropy_src_o,
  input  tlul_pkg::tl_d2h_t tl_entropy_src_i,
  output tlul_pkg::tl_h2d_t tl_csrng_o,
  input  tlul_pkg::tl_d2h_t tl_csrng_i,
  output tlul_pkg::tl_h2d_t tl_edn0_o,
  input  tlul_pkg::tl_d2h_t tl_edn0_i,
  output tlul_pkg::tl_h2d_t tl_edn1_o,
  input  tlul_pkg::tl_d2h_t tl_edn1_i,
  output tlul_pkg::tl_h2d_t tl_rv_plic_o,
  input  tlul_pkg::tl_d2h_t tl_rv_plic_i,
  output tlul_pkg::tl_h2d_t tl_otbn_o,
  input  tlul_pkg::tl_d2h_t tl_otbn_i,
  output tlul_pkg::tl_h2d_t tl_keymgr_o,
  input  tlul_pkg::tl_d2h_t tl_keymgr_i,
  output tlul_pkg::tl_h2d_t tl_sram_ctrl_main_o,
  input  tlul_pkg::tl_d2h_t tl_sram_ctrl_main_i,
  output tlul_pkg::tl_h2d_t tl_bus_ctrl_o,
  input  tlul_pkg::tl_d2h_t tl_bus_ctrl_i,
  output tlul_pkg::tl_h2d_t tl_untrusted_s_o,
  input  tlul_pkg::tl_d2h_t tl_untrusted_s_i,

  input lc_ctrl_pkg::lc_tx_t scanmode_i
);

  import tlul_pkg::*;
  import tl_main_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  lc_ctrl_pkg::lc_tx_t unused_scanmode;
  assign unused_scanmode = scanmode_i;

  tl_h2d_t tl_s1n_25_us_h2d ;
  tl_d2h_t tl_s1n_25_us_d2h ;


  tl_h2d_t tl_s1n_25_ds_h2d [4];
  tl_d2h_t tl_s1n_25_ds_d2h [4];

  // Create steering signal
  logic [2:0] dev_sel_s1n_25;


  tl_h2d_t tl_sm1_26_us_h2d [3];
  tl_d2h_t tl_sm1_26_us_d2h [3];

  tl_h2d_t tl_sm1_26_ds_h2d ;
  tl_d2h_t tl_sm1_26_ds_d2h ;


  tl_h2d_t tl_sm1_27_us_h2d [2];
  tl_d2h_t tl_sm1_27_us_d2h [2];

  tl_h2d_t tl_sm1_27_ds_h2d ;
  tl_d2h_t tl_sm1_27_ds_d2h ;


  tl_h2d_t tl_sm1_28_us_h2d [4];
  tl_d2h_t tl_sm1_28_us_d2h [4];

  tl_h2d_t tl_sm1_28_ds_h2d ;
  tl_d2h_t tl_sm1_28_ds_d2h ;


  tl_h2d_t tl_sm1_29_us_h2d [4];
  tl_d2h_t tl_sm1_29_us_d2h [4];

  tl_h2d_t tl_sm1_29_ds_h2d ;
  tl_d2h_t tl_sm1_29_ds_d2h ;

  tl_h2d_t tl_s1n_30_us_h2d ;
  tl_d2h_t tl_s1n_30_us_d2h ;


  tl_h2d_t tl_s1n_30_ds_h2d [21];
  tl_d2h_t tl_s1n_30_ds_d2h [21];

  // Create steering signal
  logic [4:0] dev_sel_s1n_30;


  tl_h2d_t tl_sm1_31_us_h2d [2];
  tl_d2h_t tl_sm1_31_us_d2h [2];

  tl_h2d_t tl_sm1_31_ds_h2d ;
  tl_d2h_t tl_sm1_31_ds_d2h ;

  tl_h2d_t tl_asf_32_secure_us_h2d ;
  tl_d2h_t tl_asf_32_secure_us_d2h ;

  tl_h2d_t tl_asf_32_secure_ds_h2d ;
  tl_d2h_t tl_asf_32_secure_ds_d2h ;

  tl_h2d_t tl_asf_32_untrusted_us_h2d ;
  tl_d2h_t tl_asf_32_untrusted_us_d2h ;

  tl_h2d_t tl_asf_32_untrusted_ds_h2d ;
  tl_d2h_t tl_asf_32_untrusted_ds_d2h ;

  tl_h2d_t tl_sm1_33_us_h2d [3];
  tl_d2h_t tl_sm1_33_us_d2h [3];

  tl_h2d_t tl_sm1_33_secure_us_h2d [3];
  tl_d2h_t tl_sm1_33_secure_us_d2h [3];

  tl_h2d_t tl_sm1_33_secure_ds_h2d ;
  tl_d2h_t tl_sm1_33_secure_ds_d2h ;

  tl_h2d_t tl_sm1_33_untrusted_us_h2d ;
  tl_d2h_t tl_sm1_33_untrusted_us_d2h ;

  tl_h2d_t tl_sm1_33_untrusted_ds_h2d ;
  tl_d2h_t tl_sm1_33_untrusted_ds_d2h ;


  tl_h2d_t tl_sm1_34_us_h2d [3];
  tl_d2h_t tl_sm1_34_us_d2h [3];

  tl_h2d_t tl_sm1_34_ds_h2d ;
  tl_d2h_t tl_sm1_34_ds_d2h ;


  tl_h2d_t tl_sm1_35_us_h2d [3];
  tl_d2h_t tl_sm1_35_us_d2h [3];

  tl_h2d_t tl_sm1_35_ds_h2d ;
  tl_d2h_t tl_sm1_35_ds_d2h ;


  tl_h2d_t tl_sm1_36_us_h2d [3];
  tl_d2h_t tl_sm1_36_us_d2h [3];

  tl_h2d_t tl_sm1_36_ds_h2d ;
  tl_d2h_t tl_sm1_36_ds_d2h ;


  tl_h2d_t tl_sm1_37_us_h2d [3];
  tl_d2h_t tl_sm1_37_us_d2h [3];

  tl_h2d_t tl_sm1_37_ds_h2d ;
  tl_d2h_t tl_sm1_37_ds_d2h ;


  tl_h2d_t tl_sm1_38_us_h2d [3];
  tl_d2h_t tl_sm1_38_us_d2h [3];

  tl_h2d_t tl_sm1_38_ds_h2d ;
  tl_d2h_t tl_sm1_38_ds_d2h ;


  tl_h2d_t tl_sm1_39_us_h2d [3];
  tl_d2h_t tl_sm1_39_us_d2h [3];

  tl_h2d_t tl_sm1_39_ds_h2d ;
  tl_d2h_t tl_sm1_39_ds_d2h ;


  tl_h2d_t tl_sm1_40_us_h2d [3];
  tl_d2h_t tl_sm1_40_us_d2h [3];

  tl_h2d_t tl_sm1_40_ds_h2d ;
  tl_d2h_t tl_sm1_40_ds_d2h ;


  tl_h2d_t tl_sm1_41_us_h2d [3];
  tl_d2h_t tl_sm1_41_us_d2h [3];

  tl_h2d_t tl_sm1_41_ds_h2d ;
  tl_d2h_t tl_sm1_41_ds_d2h ;


  tl_h2d_t tl_sm1_42_us_h2d [3];
  tl_d2h_t tl_sm1_42_us_d2h [3];

  tl_h2d_t tl_sm1_42_ds_h2d ;
  tl_d2h_t tl_sm1_42_ds_d2h ;


  tl_h2d_t tl_sm1_43_us_h2d [3];
  tl_d2h_t tl_sm1_43_us_d2h [3];

  tl_h2d_t tl_sm1_43_ds_h2d ;
  tl_d2h_t tl_sm1_43_ds_d2h ;


  tl_h2d_t tl_sm1_44_us_h2d [3];
  tl_d2h_t tl_sm1_44_us_d2h [3];

  tl_h2d_t tl_sm1_44_ds_h2d ;
  tl_d2h_t tl_sm1_44_ds_d2h ;


  tl_h2d_t tl_sm1_45_us_h2d [3];
  tl_d2h_t tl_sm1_45_us_d2h [3];

  tl_h2d_t tl_sm1_45_ds_h2d ;
  tl_d2h_t tl_sm1_45_ds_d2h ;


  tl_h2d_t tl_sm1_46_us_h2d [3];
  tl_d2h_t tl_sm1_46_us_d2h [3];

  tl_h2d_t tl_sm1_46_ds_h2d ;
  tl_d2h_t tl_sm1_46_ds_d2h ;


  tl_h2d_t tl_sm1_47_us_h2d [2];
  tl_d2h_t tl_sm1_47_us_d2h [2];

  tl_h2d_t tl_sm1_47_ds_h2d ;
  tl_d2h_t tl_sm1_47_ds_d2h ;


  tl_h2d_t tl_sm1_48_us_h2d [2];
  tl_d2h_t tl_sm1_48_us_d2h [2];

  tl_h2d_t tl_sm1_48_ds_h2d ;
  tl_d2h_t tl_sm1_48_ds_d2h ;

  tl_h2d_t tl_s1n_49_us_h2d ;
  tl_d2h_t tl_s1n_49_us_d2h ;


  tl_h2d_t tl_s1n_49_ds_h2d [20];
  tl_d2h_t tl_s1n_49_ds_d2h [20];

  // Create steering signal
  logic [4:0] dev_sel_s1n_49;

  tl_h2d_t tl_s1n_50_us_h2d ;
  tl_d2h_t tl_s1n_50_us_d2h ;


  tl_h2d_t tl_s1n_50_ds_h2d [16];
  tl_d2h_t tl_s1n_50_ds_d2h [16];

  // Create steering signal
  logic [4:0] dev_sel_s1n_50;

  logic master_bits_peri_secure_en;



  assign tl_sm1_26_us_h2d[0] = tl_s1n_25_ds_h2d[0];
  assign tl_s1n_25_ds_d2h[0] = tl_sm1_26_us_d2h[0];

  assign tl_sm1_27_us_h2d[0] = tl_s1n_25_ds_h2d[1];
  assign tl_s1n_25_ds_d2h[1] = tl_sm1_27_us_d2h[0];

  assign tl_sm1_28_us_h2d[0] = tl_s1n_25_ds_h2d[2];
  assign tl_s1n_25_ds_d2h[2] = tl_sm1_28_us_d2h[0];

  assign tl_sm1_29_us_h2d[0] = tl_s1n_25_ds_h2d[3];
  assign tl_s1n_25_ds_d2h[3] = tl_sm1_29_us_d2h[0];

  assign tl_sm1_26_us_h2d[1] = tl_s1n_30_ds_h2d[0];
  assign tl_s1n_30_ds_d2h[0] = tl_sm1_26_us_d2h[1];

  assign tl_sm1_31_us_h2d[0] = tl_s1n_30_ds_h2d[1];
  assign tl_s1n_30_ds_d2h[1] = tl_sm1_31_us_d2h[0];

  assign tl_sm1_27_us_h2d[1] = tl_s1n_30_ds_h2d[2];
  assign tl_s1n_30_ds_d2h[2] = tl_sm1_27_us_d2h[1];

  assign tl_sm1_28_us_h2d[1] = tl_s1n_30_ds_h2d[3];
  assign tl_s1n_30_ds_d2h[3] = tl_sm1_28_us_d2h[1];

  assign tl_sm1_29_us_h2d[1] = tl_s1n_30_ds_h2d[4];
  assign tl_s1n_30_ds_d2h[4] = tl_sm1_29_us_d2h[1];

  assign tl_sm1_33_us_h2d[0] = tl_s1n_30_ds_h2d[5];
  assign tl_s1n_30_ds_d2h[5] = tl_sm1_33_us_d2h[0];

  assign tl_sm1_34_us_h2d[0] = tl_s1n_30_ds_h2d[6];
  assign tl_s1n_30_ds_d2h[6] = tl_sm1_34_us_d2h[0];

  assign tl_sm1_35_us_h2d[0] = tl_s1n_30_ds_h2d[7];
  assign tl_s1n_30_ds_d2h[7] = tl_sm1_35_us_d2h[0];

  assign tl_sm1_36_us_h2d[0] = tl_s1n_30_ds_h2d[8];
  assign tl_s1n_30_ds_d2h[8] = tl_sm1_36_us_d2h[0];

  assign tl_sm1_37_us_h2d[0] = tl_s1n_30_ds_h2d[9];
  assign tl_s1n_30_ds_d2h[9] = tl_sm1_37_us_d2h[0];

  assign tl_sm1_38_us_h2d[0] = tl_s1n_30_ds_h2d[10];
  assign tl_s1n_30_ds_d2h[10] = tl_sm1_38_us_d2h[0];

  assign tl_sm1_39_us_h2d[0] = tl_s1n_30_ds_h2d[11];
  assign tl_s1n_30_ds_d2h[11] = tl_sm1_39_us_d2h[0];

  assign tl_sm1_40_us_h2d[0] = tl_s1n_30_ds_h2d[12];
  assign tl_s1n_30_ds_d2h[12] = tl_sm1_40_us_d2h[0];

  assign tl_sm1_41_us_h2d[0] = tl_s1n_30_ds_h2d[13];
  assign tl_s1n_30_ds_d2h[13] = tl_sm1_41_us_d2h[0];

  assign tl_sm1_42_us_h2d[0] = tl_s1n_30_ds_h2d[14];
  assign tl_s1n_30_ds_d2h[14] = tl_sm1_42_us_d2h[0];

  assign tl_sm1_43_us_h2d[0] = tl_s1n_30_ds_h2d[15];
  assign tl_s1n_30_ds_d2h[15] = tl_sm1_43_us_d2h[0];

  assign tl_sm1_44_us_h2d[0] = tl_s1n_30_ds_h2d[16];
  assign tl_s1n_30_ds_d2h[16] = tl_sm1_44_us_d2h[0];

  assign tl_sm1_45_us_h2d[0] = tl_s1n_30_ds_h2d[17];
  assign tl_s1n_30_ds_d2h[17] = tl_sm1_45_us_d2h[0];

  assign tl_sm1_46_us_h2d[0] = tl_s1n_30_ds_h2d[18];
  assign tl_s1n_30_ds_d2h[18] = tl_sm1_46_us_d2h[0];

  assign tl_sm1_47_us_h2d[0] = tl_s1n_30_ds_h2d[19];
  assign tl_s1n_30_ds_d2h[19] = tl_sm1_47_us_d2h[0];

  assign tl_sm1_48_us_h2d[0] = tl_s1n_30_ds_h2d[20];
  assign tl_s1n_30_ds_d2h[20] = tl_sm1_48_us_d2h[0];

  assign tl_sm1_26_us_h2d[2] = tl_s1n_49_ds_h2d[0];
  assign tl_s1n_49_ds_d2h[0] = tl_sm1_26_us_d2h[2];

  assign tl_sm1_31_us_h2d[1] = tl_s1n_49_ds_h2d[1];
  assign tl_s1n_49_ds_d2h[1] = tl_sm1_31_us_d2h[1];

  assign tl_sm1_28_us_h2d[2] = tl_s1n_49_ds_h2d[2];
  assign tl_s1n_49_ds_d2h[2] = tl_sm1_28_us_d2h[2];

  assign tl_sm1_29_us_h2d[2] = tl_s1n_49_ds_h2d[3];
  assign tl_s1n_49_ds_d2h[3] = tl_sm1_29_us_d2h[2];

  assign tl_sm1_33_us_h2d[1] = tl_s1n_49_ds_h2d[4];
  assign tl_s1n_49_ds_d2h[4] = tl_sm1_33_us_d2h[1];

  assign tl_sm1_34_us_h2d[1] = tl_s1n_49_ds_h2d[5];
  assign tl_s1n_49_ds_d2h[5] = tl_sm1_34_us_d2h[1];

  assign tl_sm1_35_us_h2d[1] = tl_s1n_49_ds_h2d[6];
  assign tl_s1n_49_ds_d2h[6] = tl_sm1_35_us_d2h[1];

  assign tl_sm1_36_us_h2d[1] = tl_s1n_49_ds_h2d[7];
  assign tl_s1n_49_ds_d2h[7] = tl_sm1_36_us_d2h[1];

  assign tl_sm1_37_us_h2d[1] = tl_s1n_49_ds_h2d[8];
  assign tl_s1n_49_ds_d2h[8] = tl_sm1_37_us_d2h[1];

  assign tl_sm1_38_us_h2d[1] = tl_s1n_49_ds_h2d[9];
  assign tl_s1n_49_ds_d2h[9] = tl_sm1_38_us_d2h[1];

  assign tl_sm1_39_us_h2d[1] = tl_s1n_49_ds_h2d[10];
  assign tl_s1n_49_ds_d2h[10] = tl_sm1_39_us_d2h[1];

  assign tl_sm1_40_us_h2d[1] = tl_s1n_49_ds_h2d[11];
  assign tl_s1n_49_ds_d2h[11] = tl_sm1_40_us_d2h[1];

  assign tl_sm1_41_us_h2d[1] = tl_s1n_49_ds_h2d[12];
  assign tl_s1n_49_ds_d2h[12] = tl_sm1_41_us_d2h[1];

  assign tl_sm1_42_us_h2d[1] = tl_s1n_49_ds_h2d[13];
  assign tl_s1n_49_ds_d2h[13] = tl_sm1_42_us_d2h[1];

  assign tl_sm1_43_us_h2d[1] = tl_s1n_49_ds_h2d[14];
  assign tl_s1n_49_ds_d2h[14] = tl_sm1_43_us_d2h[1];

  assign tl_sm1_44_us_h2d[1] = tl_s1n_49_ds_h2d[15];
  assign tl_s1n_49_ds_d2h[15] = tl_sm1_44_us_d2h[1];

  assign tl_sm1_45_us_h2d[1] = tl_s1n_49_ds_h2d[16];
  assign tl_s1n_49_ds_d2h[16] = tl_sm1_45_us_d2h[1];

  assign tl_sm1_46_us_h2d[1] = tl_s1n_49_ds_h2d[17];
  assign tl_s1n_49_ds_d2h[17] = tl_sm1_46_us_d2h[1];

  assign tl_sm1_47_us_h2d[1] = tl_s1n_49_ds_h2d[18];
  assign tl_s1n_49_ds_d2h[18] = tl_sm1_47_us_d2h[1];

  assign tl_sm1_48_us_h2d[1] = tl_s1n_49_ds_h2d[19];
  assign tl_s1n_49_ds_d2h[19] = tl_sm1_48_us_d2h[1];

  assign tl_sm1_28_us_h2d[3] = tl_s1n_50_ds_h2d[0];
  assign tl_s1n_50_ds_d2h[0] = tl_sm1_28_us_d2h[3];

  assign tl_sm1_29_us_h2d[3] = tl_s1n_50_ds_h2d[1];
  assign tl_s1n_50_ds_d2h[1] = tl_sm1_29_us_d2h[3];

  assign tl_sm1_33_us_h2d[2] = tl_s1n_50_ds_h2d[2];
  assign tl_s1n_50_ds_d2h[2] = tl_sm1_33_us_d2h[2];

  assign tl_sm1_34_us_h2d[2] = tl_s1n_50_ds_h2d[3];
  assign tl_s1n_50_ds_d2h[3] = tl_sm1_34_us_d2h[2];

  assign tl_sm1_35_us_h2d[2] = tl_s1n_50_ds_h2d[4];
  assign tl_s1n_50_ds_d2h[4] = tl_sm1_35_us_d2h[2];

  assign tl_sm1_36_us_h2d[2] = tl_s1n_50_ds_h2d[5];
  assign tl_s1n_50_ds_d2h[5] = tl_sm1_36_us_d2h[2];

  assign tl_sm1_37_us_h2d[2] = tl_s1n_50_ds_h2d[6];
  assign tl_s1n_50_ds_d2h[6] = tl_sm1_37_us_d2h[2];

  assign tl_sm1_38_us_h2d[2] = tl_s1n_50_ds_h2d[7];
  assign tl_s1n_50_ds_d2h[7] = tl_sm1_38_us_d2h[2];

  assign tl_sm1_39_us_h2d[2] = tl_s1n_50_ds_h2d[8];
  assign tl_s1n_50_ds_d2h[8] = tl_sm1_39_us_d2h[2];

  assign tl_sm1_40_us_h2d[2] = tl_s1n_50_ds_h2d[9];
  assign tl_s1n_50_ds_d2h[9] = tl_sm1_40_us_d2h[2];

  assign tl_sm1_41_us_h2d[2] = tl_s1n_50_ds_h2d[10];
  assign tl_s1n_50_ds_d2h[10] = tl_sm1_41_us_d2h[2];

  assign tl_sm1_42_us_h2d[2] = tl_s1n_50_ds_h2d[11];
  assign tl_s1n_50_ds_d2h[11] = tl_sm1_42_us_d2h[2];

  assign tl_sm1_43_us_h2d[2] = tl_s1n_50_ds_h2d[12];
  assign tl_s1n_50_ds_d2h[12] = tl_sm1_43_us_d2h[2];

  assign tl_sm1_44_us_h2d[2] = tl_s1n_50_ds_h2d[13];
  assign tl_s1n_50_ds_d2h[13] = tl_sm1_44_us_d2h[2];

  assign tl_sm1_45_us_h2d[2] = tl_s1n_50_ds_h2d[14];
  assign tl_s1n_50_ds_d2h[14] = tl_sm1_45_us_d2h[2];

  assign tl_sm1_46_us_h2d[2] = tl_s1n_50_ds_h2d[15];
  assign tl_s1n_50_ds_d2h[15] = tl_sm1_46_us_d2h[2];

  assign tl_s1n_25_us_h2d = tl_corei_i;
  assign tl_corei_o = tl_s1n_25_us_d2h;

  assign tl_rom_ctrl__rom_o = tl_sm1_26_ds_h2d;
  assign tl_sm1_26_ds_d2h = tl_rom_ctrl__rom_i;

  assign tl_debug_mem_o = tl_sm1_27_ds_h2d;
  assign tl_sm1_27_ds_d2h = tl_debug_mem_i;

  assign tl_ram_main_o = tl_sm1_28_ds_h2d;
  assign tl_sm1_28_ds_d2h = tl_ram_main_i;

  assign tl_eflash_o = tl_sm1_29_ds_h2d;
  assign tl_sm1_29_ds_d2h = tl_eflash_i;

  assign tl_s1n_30_us_h2d = tl_cored_i;
  assign tl_cored_o = tl_s1n_30_us_d2h;

  assign tl_rom_ctrl__regs_o = tl_sm1_31_ds_h2d;
  assign tl_sm1_31_ds_d2h = tl_rom_ctrl__regs_i;

  assign tl_peri_secure_o = tl_asf_32_secure_ds_h2d;
  assign tl_asf_32_secure_ds_d2h = tl_peri_secure_i;

  assign tl_peri_untrusted_o = tl_asf_32_untrusted_ds_h2d;
  assign tl_asf_32_untrusted_ds_d2h = tl_peri_untrusted_i;

  assign tl_asf_32_secure_us_h2d = tl_sm1_33_secure_ds_h2d;
  assign tl_sm1_33_secure_ds_d2h = tl_asf_32_secure_us_d2h;

  assign tl_asf_32_untrusted_us_h2d = tl_sm1_33_untrusted_ds_h2d;
  assign tl_sm1_33_untrusted_ds_d2h = tl_asf_32_untrusted_us_d2h;

  assign tl_flash_ctrl__core_o = tl_sm1_34_ds_h2d;
  assign tl_sm1_34_ds_d2h = tl_flash_ctrl__core_i;

  assign tl_flash_ctrl__prim_o = tl_sm1_35_ds_h2d;
  assign tl_sm1_35_ds_d2h = tl_flash_ctrl__prim_i;

  assign tl_aes_o = tl_sm1_36_ds_h2d;
  assign tl_sm1_36_ds_d2h = tl_aes_i;

  assign tl_entropy_src_o = tl_sm1_37_ds_h2d;
  assign tl_sm1_37_ds_d2h = tl_entropy_src_i;

  assign tl_csrng_o = tl_sm1_38_ds_h2d;
  assign tl_sm1_38_ds_d2h = tl_csrng_i;

  assign tl_edn0_o = tl_sm1_39_ds_h2d;
  assign tl_sm1_39_ds_d2h = tl_edn0_i;

  assign tl_edn1_o = tl_sm1_40_ds_h2d;
  assign tl_sm1_40_ds_d2h = tl_edn1_i;

  assign tl_hmac_o = tl_sm1_41_ds_h2d;
  assign tl_sm1_41_ds_d2h = tl_hmac_i;

  assign tl_rv_plic_o = tl_sm1_42_ds_h2d;
  assign tl_sm1_42_ds_d2h = tl_rv_plic_i;

  assign tl_otbn_o = tl_sm1_43_ds_h2d;
  assign tl_sm1_43_ds_d2h = tl_otbn_i;

  assign tl_keymgr_o = tl_sm1_44_ds_h2d;
  assign tl_sm1_44_ds_d2h = tl_keymgr_i;

  assign tl_kmac_o = tl_sm1_45_ds_h2d;
  assign tl_sm1_45_ds_d2h = tl_kmac_i;

  assign tl_sram_ctrl_main_o = tl_sm1_46_ds_h2d;
  assign tl_sm1_46_ds_d2h = tl_sram_ctrl_main_i;

  assign tl_bus_ctrl_o = tl_sm1_47_ds_h2d;
  assign tl_sm1_47_ds_d2h = tl_bus_ctrl_i;

  assign tl_untrusted_s_o = tl_sm1_48_ds_h2d;
  assign tl_sm1_48_ds_d2h = tl_untrusted_s_i;

  assign tl_s1n_49_us_h2d = tl_dm_sba_i;
  assign tl_dm_sba_o = tl_s1n_49_us_d2h;

  assign tl_s1n_50_us_h2d = tl_untrusted_m_i;
  assign tl_untrusted_m_o = tl_s1n_50_us_d2h;

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_25 = 3'd4;
    if ((tl_s1n_25_us_h2d.a_address &
         ~(ADDR_MASK_ROM_CTRL__ROM)) == ADDR_SPACE_ROM_CTRL__ROM) begin
      dev_sel_s1n_25 = 3'd0;

    end else if ((tl_s1n_25_us_h2d.a_address &
                  ~(ADDR_MASK_DEBUG_MEM)) == ADDR_SPACE_DEBUG_MEM) begin
      dev_sel_s1n_25 = 3'd1;

    end else if ((tl_s1n_25_us_h2d.a_address &
                  ~(ADDR_MASK_RAM_MAIN)) == ADDR_SPACE_RAM_MAIN) begin
      dev_sel_s1n_25 = 3'd2;

    end else if ((tl_s1n_25_us_h2d.a_address &
                  ~(ADDR_MASK_EFLASH)) == ADDR_SPACE_EFLASH) begin
      dev_sel_s1n_25 = 3'd3;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_30 = 5'd21;
    if ((tl_s1n_30_us_h2d.a_address &
         ~(ADDR_MASK_ROM_CTRL__ROM)) == ADDR_SPACE_ROM_CTRL__ROM) begin
      dev_sel_s1n_30 = 5'd0;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_ROM_CTRL__REGS)) == ADDR_SPACE_ROM_CTRL__REGS) begin
      dev_sel_s1n_30 = 5'd1;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_DEBUG_MEM)) == ADDR_SPACE_DEBUG_MEM) begin
      dev_sel_s1n_30 = 5'd2;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_RAM_MAIN)) == ADDR_SPACE_RAM_MAIN) begin
      dev_sel_s1n_30 = 5'd3;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_EFLASH)) == ADDR_SPACE_EFLASH) begin
      dev_sel_s1n_30 = 5'd4;

    end else if (
      ((tl_s1n_30_us_h2d.a_address & ~(ADDR_MASK_PERI[0])) == ADDR_SPACE_PERI[0]) ||
      ((tl_s1n_30_us_h2d.a_address & ~(ADDR_MASK_PERI[1])) == ADDR_SPACE_PERI[1])
    ) begin
      dev_sel_s1n_30 = 5'd5;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_FLASH_CTRL__CORE)) == ADDR_SPACE_FLASH_CTRL__CORE) begin
      dev_sel_s1n_30 = 5'd6;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_FLASH_CTRL__PRIM)) == ADDR_SPACE_FLASH_CTRL__PRIM) begin
      dev_sel_s1n_30 = 5'd7;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_AES)) == ADDR_SPACE_AES) begin
      dev_sel_s1n_30 = 5'd8;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_ENTROPY_SRC)) == ADDR_SPACE_ENTROPY_SRC) begin
      dev_sel_s1n_30 = 5'd9;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_CSRNG)) == ADDR_SPACE_CSRNG) begin
      dev_sel_s1n_30 = 5'd10;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_EDN0)) == ADDR_SPACE_EDN0) begin
      dev_sel_s1n_30 = 5'd11;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_EDN1)) == ADDR_SPACE_EDN1) begin
      dev_sel_s1n_30 = 5'd12;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_HMAC)) == ADDR_SPACE_HMAC) begin
      dev_sel_s1n_30 = 5'd13;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_RV_PLIC)) == ADDR_SPACE_RV_PLIC) begin
      dev_sel_s1n_30 = 5'd14;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_OTBN)) == ADDR_SPACE_OTBN) begin
      dev_sel_s1n_30 = 5'd15;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_KEYMGR)) == ADDR_SPACE_KEYMGR) begin
      dev_sel_s1n_30 = 5'd16;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_KMAC)) == ADDR_SPACE_KMAC) begin
      dev_sel_s1n_30 = 5'd17;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_MAIN)) == ADDR_SPACE_SRAM_CTRL_MAIN) begin
      dev_sel_s1n_30 = 5'd18;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_BUS_CTRL)) == ADDR_SPACE_BUS_CTRL) begin
      dev_sel_s1n_30 = 5'd19;

    end else if ((tl_s1n_30_us_h2d.a_address &
                  ~(ADDR_MASK_UNTRUSTED_S)) == ADDR_SPACE_UNTRUSTED_S) begin
      dev_sel_s1n_30 = 5'd20;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_49 = 5'd20;
    if ((tl_s1n_49_us_h2d.a_address &
         ~(ADDR_MASK_ROM_CTRL__ROM)) == ADDR_SPACE_ROM_CTRL__ROM) begin
      dev_sel_s1n_49 = 5'd0;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_ROM_CTRL__REGS)) == ADDR_SPACE_ROM_CTRL__REGS) begin
      dev_sel_s1n_49 = 5'd1;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_RAM_MAIN)) == ADDR_SPACE_RAM_MAIN) begin
      dev_sel_s1n_49 = 5'd2;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_EFLASH)) == ADDR_SPACE_EFLASH) begin
      dev_sel_s1n_49 = 5'd3;

    end else if (
      ((tl_s1n_49_us_h2d.a_address & ~(ADDR_MASK_PERI[0])) == ADDR_SPACE_PERI[0]) ||
      ((tl_s1n_49_us_h2d.a_address & ~(ADDR_MASK_PERI[1])) == ADDR_SPACE_PERI[1])
    ) begin
      dev_sel_s1n_49 = 5'd4;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_FLASH_CTRL__CORE)) == ADDR_SPACE_FLASH_CTRL__CORE) begin
      dev_sel_s1n_49 = 5'd5;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_FLASH_CTRL__PRIM)) == ADDR_SPACE_FLASH_CTRL__PRIM) begin
      dev_sel_s1n_49 = 5'd6;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_AES)) == ADDR_SPACE_AES) begin
      dev_sel_s1n_49 = 5'd7;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_ENTROPY_SRC)) == ADDR_SPACE_ENTROPY_SRC) begin
      dev_sel_s1n_49 = 5'd8;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_CSRNG)) == ADDR_SPACE_CSRNG) begin
      dev_sel_s1n_49 = 5'd9;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_EDN0)) == ADDR_SPACE_EDN0) begin
      dev_sel_s1n_49 = 5'd10;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_EDN1)) == ADDR_SPACE_EDN1) begin
      dev_sel_s1n_49 = 5'd11;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_HMAC)) == ADDR_SPACE_HMAC) begin
      dev_sel_s1n_49 = 5'd12;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_RV_PLIC)) == ADDR_SPACE_RV_PLIC) begin
      dev_sel_s1n_49 = 5'd13;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_OTBN)) == ADDR_SPACE_OTBN) begin
      dev_sel_s1n_49 = 5'd14;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_KEYMGR)) == ADDR_SPACE_KEYMGR) begin
      dev_sel_s1n_49 = 5'd15;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_KMAC)) == ADDR_SPACE_KMAC) begin
      dev_sel_s1n_49 = 5'd16;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_MAIN)) == ADDR_SPACE_SRAM_CTRL_MAIN) begin
      dev_sel_s1n_49 = 5'd17;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_BUS_CTRL)) == ADDR_SPACE_BUS_CTRL) begin
      dev_sel_s1n_49 = 5'd18;

    end else if ((tl_s1n_49_us_h2d.a_address &
                  ~(ADDR_MASK_UNTRUSTED_S)) == ADDR_SPACE_UNTRUSTED_S) begin
      dev_sel_s1n_49 = 5'd19;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_50 = 5'd16;
    // extra protection mechanism from bus_ctrl registers is implemented
    master_bits_peri_secure_en = '0;
    if ((tl_s1n_50_us_h2d.a_address &
         ~(ADDR_MASK_RAM_MAIN)) == ADDR_SPACE_RAM_MAIN &&
         master_bits_i.untrusted_m == slave_bits_i.ram_main) begin
      dev_sel_s1n_50 = 5'd0;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_EFLASH)) == ADDR_SPACE_EFLASH &&
                  master_bits_i.untrusted_m == slave_bits_i.eflash) begin
      dev_sel_s1n_50 = 5'd1;

    end else if (
      ((tl_s1n_50_us_h2d.a_address & ~(ADDR_MASK_PERI[0])) == ADDR_SPACE_PERI[0]) ||
      ((tl_s1n_50_us_h2d.a_address & ~(ADDR_MASK_PERI[1])) == ADDR_SPACE_PERI[1])) begin
      dev_sel_s1n_50      = 5'd2;
      master_bits_peri_secure_en = tl_untrusted_m_i.a_valid & tl_untrusted_m_o.a_ready & master_bits_i.untrusted_m;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_FLASH_CTRL__CORE)) == ADDR_SPACE_FLASH_CTRL__CORE &&
                  master_bits_i.untrusted_m == slave_bits_i.flash_ctrl_core) begin
      dev_sel_s1n_50 = 5'd3;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_FLASH_CTRL__PRIM)) == ADDR_SPACE_FLASH_CTRL__PRIM &&
                  master_bits_i.untrusted_m == slave_bits_i.flash_ctrl_prim) begin
      dev_sel_s1n_50 = 5'd4;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_AES)) == ADDR_SPACE_AES &&
                  master_bits_i.untrusted_m == slave_bits_i.aes) begin
      dev_sel_s1n_50 = 5'd5;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ENTROPY_SRC)) == ADDR_SPACE_ENTROPY_SRC &&
                  master_bits_i.untrusted_m == slave_bits_i.entropy_src) begin
      dev_sel_s1n_50 = 5'd6;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_CSRNG)) == ADDR_SPACE_CSRNG &&
                  master_bits_i.untrusted_m == slave_bits_i.csrng) begin
      dev_sel_s1n_50 = 5'd7;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_EDN0)) == ADDR_SPACE_EDN0 &&
                  master_bits_i.untrusted_m == slave_bits_i.edn0) begin
      dev_sel_s1n_50 = 5'd8;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_EDN1)) == ADDR_SPACE_EDN1 &&
                  master_bits_i.untrusted_m == slave_bits_i.edn1) begin
      dev_sel_s1n_50 = 5'd9;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_HMAC)) == ADDR_SPACE_HMAC &&
                  master_bits_i.untrusted_m == slave_bits_i.hmac) begin
      dev_sel_s1n_50 = 5'd10;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_RV_PLIC)) == ADDR_SPACE_RV_PLIC &&
                  master_bits_i.untrusted_m == slave_bits_i.rv_plic) begin
      dev_sel_s1n_50 = 5'd11;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_OTBN)) == ADDR_SPACE_OTBN &&
                  master_bits_i.untrusted_m == slave_bits_i.otbn) begin
      dev_sel_s1n_50 = 5'd12;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_KEYMGR)) == ADDR_SPACE_KEYMGR &&
                  master_bits_i.untrusted_m == slave_bits_i.keymgr) begin
      dev_sel_s1n_50 = 5'd13;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_KMAC)) == ADDR_SPACE_KMAC &&
                  master_bits_i.untrusted_m == slave_bits_i.kmac) begin
      dev_sel_s1n_50 = 5'd14;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_MAIN)) == ADDR_SPACE_SRAM_CTRL_MAIN &&
                  master_bits_i.untrusted_m == slave_bits_i.sram_ctrl_main) begin
      dev_sel_s1n_50 = 5'd15;
end
  end


  // Instantiation phase
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (16'h0),
    .DRspDepth (16'h0),
    .N         (4)
  ) u_s1n_25 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_25_us_h2d),
    .tl_h_o       (tl_s1n_25_us_d2h),
    .tl_d_o       (tl_s1n_25_ds_h2d),
    .tl_d_i       (tl_s1n_25_ds_d2h),
    .dev_select_i (dev_sel_s1n_25)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (3)
  ) u_sm1_26 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_26_us_h2d),
    .tl_h_o       (tl_sm1_26_us_d2h),
    .tl_d_o       (tl_sm1_26_ds_h2d),
    .tl_d_i       (tl_sm1_26_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (2)
  ) u_sm1_27 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_27_us_h2d),
    .tl_h_o       (tl_sm1_27_us_d2h),
    .tl_d_o       (tl_sm1_27_ds_h2d),
    .tl_d_i       (tl_sm1_27_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (16'h0),
    .HRspDepth (16'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (4)
  ) u_sm1_28 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_28_us_h2d),
    .tl_h_o       (tl_sm1_28_us_d2h),
    .tl_d_o       (tl_sm1_28_ds_h2d),
    .tl_d_i       (tl_sm1_28_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (16'h0),
    .HRspDepth (16'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (4)
  ) u_sm1_29 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_29_us_h2d),
    .tl_h_o       (tl_sm1_29_us_d2h),
    .tl_d_o       (tl_sm1_29_ds_h2d),
    .tl_d_i       (tl_sm1_29_ds_d2h)
  );
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (84'h0),
    .DRspDepth (84'h0),
    .N         (21)
  ) u_s1n_30 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_30_us_h2d),
    .tl_h_o       (tl_s1n_30_us_d2h),
    .tl_d_o       (tl_s1n_30_ds_h2d),
    .tl_d_i       (tl_s1n_30_ds_d2h),
    .dev_select_i (dev_sel_s1n_30)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_31 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_31_us_h2d),
    .tl_h_o       (tl_sm1_31_us_d2h),
    .tl_d_o       (tl_sm1_31_ds_h2d),
    .tl_d_i       (tl_sm1_31_ds_d2h)
  );

  tlul_fifo_async #(
    .ReqDepth        (4),// At least 4 to make async work
    .RspDepth        (4)// At least 4 to make async work
  ) u_asf_32_secure (
    .clk_h_i      (clk_main_i),
    .rst_h_ni     (rst_main_ni),
    .clk_d_i      (clk_fixed_i),
    .rst_d_ni     (rst_fixed_ni),
    .tl_h_i       (tl_asf_32_secure_us_h2d),
    .tl_h_o       (tl_asf_32_secure_us_d2h),
    .tl_d_o       (tl_asf_32_secure_ds_h2d),
    .tl_d_i       (tl_asf_32_secure_ds_d2h),
    .spare_req_i  (master_bits_peri_secure_en),
    .spare_req_o  (master_bit_peri_secure_en_o),
    .spare_rsp_i  (1'b0),
    .spare_rsp_o  ()
  );
  tlul_fifo_async #(
    .ReqDepth        (4),// At least 4 to make async work
    .RspDepth        (4) // At least 4 to make async work
  ) u_asf_32_untrusted (
    .clk_h_i      (clk_main_i),
    .rst_h_ni     (rst_main_ni),
    .clk_d_i      (clk_fixed_i),
    .rst_d_ni     (rst_fixed_ni),
    .tl_h_i       (tl_asf_32_untrusted_us_h2d),
    .tl_h_o       (tl_asf_32_untrusted_us_d2h),
    .tl_d_o       (tl_asf_32_untrusted_ds_h2d),
    .tl_d_i       (tl_asf_32_untrusted_ds_d2h),
    .spare_req_i  (1'b0),
    .spare_req_o  (),
    .spare_rsp_i  (1'b0),
    .spare_rsp_o  ()
  );

  // All master messages to/from the peripheral crossbar are routed to/from a secure or untrusted line
  assign tl_sm1_33_secure_us_h2d[0:1] = tl_sm1_33_us_h2d[0:1];
  assign tl_sm1_33_us_d2h[0:1]        = tl_sm1_33_secure_us_d2h[0:1];

  always_comb begin
    if (master_bits_i.untrusted_m) begin
      tl_sm1_33_secure_us_h2d[2].a_valid      = tl_sm1_33_us_h2d[2].a_valid;
      tl_sm1_33_secure_us_h2d[2].a_opcode     = tl_sm1_33_us_h2d[2].a_opcode;
      tl_sm1_33_secure_us_h2d[2].a_param      = tl_sm1_33_us_h2d[2].a_param;
      tl_sm1_33_secure_us_h2d[2].a_size       = tl_sm1_33_us_h2d[2].a_size;
      tl_sm1_33_secure_us_h2d[2].a_source     = tl_sm1_33_us_h2d[2].a_source;
      tl_sm1_33_secure_us_h2d[2].a_address    = tl_sm1_33_us_h2d[2].a_address;
      tl_sm1_33_secure_us_h2d[2].a_mask       = tl_sm1_33_us_h2d[2].a_mask;
      tl_sm1_33_secure_us_h2d[2].a_data       = tl_sm1_33_us_h2d[2].a_data;
      tl_sm1_33_secure_us_h2d[2].a_user       = tl_sm1_33_us_h2d[2].a_user;
      tl_sm1_33_us_d2h[2].a_ready             = tl_sm1_33_secure_us_d2h[2].a_ready;

      tl_sm1_33_untrusted_us_h2d.a_valid   = '0;
      tl_sm1_33_untrusted_us_h2d.a_opcode  = '0;
      tl_sm1_33_untrusted_us_h2d.a_param   = '0;
      tl_sm1_33_untrusted_us_h2d.a_size    = '0;
      tl_sm1_33_untrusted_us_h2d.a_source  = '0;
      tl_sm1_33_untrusted_us_h2d.a_address = '0;
      tl_sm1_33_untrusted_us_h2d.a_mask    = '0;
      tl_sm1_33_untrusted_us_h2d.a_data    = '0;
      tl_sm1_33_untrusted_us_h2d.a_user    = '0;

    end else begin
      tl_sm1_33_untrusted_us_h2d.a_valid   = tl_sm1_33_us_h2d[2].a_valid;
      tl_sm1_33_untrusted_us_h2d.a_opcode  = tl_sm1_33_us_h2d[2].a_opcode;
      tl_sm1_33_untrusted_us_h2d.a_param   = tl_sm1_33_us_h2d[2].a_param;
      tl_sm1_33_untrusted_us_h2d.a_size    = tl_sm1_33_us_h2d[2].a_size;
      tl_sm1_33_untrusted_us_h2d.a_source  = tl_sm1_33_us_h2d[2].a_source;
      tl_sm1_33_untrusted_us_h2d.a_address = tl_sm1_33_us_h2d[2].a_address;
      tl_sm1_33_untrusted_us_h2d.a_mask    = tl_sm1_33_us_h2d[2].a_mask;
      tl_sm1_33_untrusted_us_h2d.a_data    = tl_sm1_33_us_h2d[2].a_data;
      tl_sm1_33_untrusted_us_h2d.a_user    = tl_sm1_33_us_h2d[2].a_user;
      tl_sm1_33_us_d2h[2].a_ready          = tl_sm1_33_untrusted_us_d2h.a_ready;

      tl_sm1_33_secure_us_h2d[2].a_valid      = '0;
      tl_sm1_33_secure_us_h2d[2].a_opcode     = '0;
      tl_sm1_33_secure_us_h2d[2].a_param      = '0;
      tl_sm1_33_secure_us_h2d[2].a_size       = '0;
      tl_sm1_33_secure_us_h2d[2].a_source     = '0;
      tl_sm1_33_secure_us_h2d[2].a_address    = '0;
      tl_sm1_33_secure_us_h2d[2].a_mask       = '0;
      tl_sm1_33_secure_us_h2d[2].a_data       = '0;
      tl_sm1_33_secure_us_h2d[2].a_user       = '0;
    end
  end

  always_comb begin
    if (tl_sm1_33_secure_us_d2h[2].d_valid) begin
      tl_sm1_33_us_d2h[2].d_valid           = tl_sm1_33_secure_us_d2h[2].d_valid;
      tl_sm1_33_us_d2h[2].d_opcode          = tl_sm1_33_secure_us_d2h[2].d_opcode;
      tl_sm1_33_us_d2h[2].d_param           = tl_sm1_33_secure_us_d2h[2].d_param;
      tl_sm1_33_us_d2h[2].d_size            = tl_sm1_33_secure_us_d2h[2].d_size;
      tl_sm1_33_us_d2h[2].d_source          = tl_sm1_33_secure_us_d2h[2].d_source;
      tl_sm1_33_us_d2h[2].d_sink            = tl_sm1_33_secure_us_d2h[2].d_sink;
      tl_sm1_33_us_d2h[2].d_data            = tl_sm1_33_secure_us_d2h[2].d_data;
      tl_sm1_33_us_d2h[2].d_user            = tl_sm1_33_secure_us_d2h[2].d_user;
      tl_sm1_33_us_d2h[2].d_error           = tl_sm1_33_secure_us_d2h[2].d_error;
      tl_sm1_33_secure_us_h2d[2].d_ready    = tl_sm1_33_us_h2d[2].d_ready;
      tl_sm1_33_untrusted_us_h2d.d_ready = 1'b0;
    end else begin
      tl_sm1_33_us_d2h[2].d_valid           = tl_sm1_33_untrusted_us_d2h.d_valid;
      tl_sm1_33_us_d2h[2].d_opcode          = tl_sm1_33_untrusted_us_d2h.d_opcode;
      tl_sm1_33_us_d2h[2].d_param           = tl_sm1_33_untrusted_us_d2h.d_param;
      tl_sm1_33_us_d2h[2].d_size            = tl_sm1_33_untrusted_us_d2h.d_size;
      tl_sm1_33_us_d2h[2].d_source          = tl_sm1_33_untrusted_us_d2h.d_source;
      tl_sm1_33_us_d2h[2].d_sink            = tl_sm1_33_untrusted_us_d2h.d_sink;
      tl_sm1_33_us_d2h[2].d_data            = tl_sm1_33_untrusted_us_d2h.d_data;
      tl_sm1_33_us_d2h[2].d_user            = tl_sm1_33_untrusted_us_d2h.d_user;
      tl_sm1_33_us_d2h[2].d_error           = tl_sm1_33_untrusted_us_d2h.d_error;
      tl_sm1_33_untrusted_us_h2d.d_ready = tl_sm1_33_us_h2d[2].d_ready;
      tl_sm1_33_secure_us_h2d[2].d_ready    = 1'b0;
  end
end

  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (3)
  ) u_sm1_33_secure (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_33_secure_us_h2d),
    .tl_h_o       (tl_sm1_33_secure_us_d2h),
    .tl_d_o       (tl_sm1_33_secure_ds_h2d),
    .tl_d_i       (tl_sm1_33_secure_ds_d2h)
  );

  assign tl_sm1_33_untrusted_ds_h2d = tl_sm1_33_untrusted_us_h2d;
  assign tl_sm1_33_untrusted_us_d2h = tl_sm1_33_untrusted_ds_d2h;

  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_34 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_34_us_h2d),
    .tl_h_o       (tl_sm1_34_us_d2h),
    .tl_d_o       (tl_sm1_34_ds_h2d),
    .tl_d_i       (tl_sm1_34_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_35 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_35_us_h2d),
    .tl_h_o       (tl_sm1_35_us_d2h),
    .tl_d_o       (tl_sm1_35_ds_h2d),
    .tl_d_i       (tl_sm1_35_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_36 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_36_us_h2d),
    .tl_h_o       (tl_sm1_36_us_d2h),
    .tl_d_o       (tl_sm1_36_ds_h2d),
    .tl_d_i       (tl_sm1_36_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_37 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_37_us_h2d),
    .tl_h_o       (tl_sm1_37_us_d2h),
    .tl_d_o       (tl_sm1_37_ds_h2d),
    .tl_d_i       (tl_sm1_37_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_38 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_38_us_h2d),
    .tl_h_o       (tl_sm1_38_us_d2h),
    .tl_d_o       (tl_sm1_38_ds_h2d),
    .tl_d_i       (tl_sm1_38_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_39 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_39_us_h2d),
    .tl_h_o       (tl_sm1_39_us_d2h),
    .tl_d_o       (tl_sm1_39_ds_h2d),
    .tl_d_i       (tl_sm1_39_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_40 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_40_us_h2d),
    .tl_h_o       (tl_sm1_40_us_d2h),
    .tl_d_o       (tl_sm1_40_ds_h2d),
    .tl_d_i       (tl_sm1_40_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_41 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_41_us_h2d),
    .tl_h_o       (tl_sm1_41_us_d2h),
    .tl_d_o       (tl_sm1_41_ds_h2d),
    .tl_d_i       (tl_sm1_41_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_42 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_42_us_h2d),
    .tl_h_o       (tl_sm1_42_us_d2h),
    .tl_d_o       (tl_sm1_42_ds_h2d),
    .tl_d_i       (tl_sm1_42_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_43 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_43_us_h2d),
    .tl_h_o       (tl_sm1_43_us_d2h),
    .tl_d_o       (tl_sm1_43_ds_h2d),
    .tl_d_i       (tl_sm1_43_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_44 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_44_us_h2d),
    .tl_h_o       (tl_sm1_44_us_d2h),
    .tl_d_o       (tl_sm1_44_ds_h2d),
    .tl_d_i       (tl_sm1_44_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_45 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_45_us_h2d),
    .tl_h_o       (tl_sm1_45_us_d2h),
    .tl_d_o       (tl_sm1_45_ds_h2d),
    .tl_d_i       (tl_sm1_45_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (3)
  ) u_sm1_46 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_46_us_h2d),
    .tl_h_o       (tl_sm1_46_us_d2h),
    .tl_d_o       (tl_sm1_46_ds_h2d),
    .tl_d_i       (tl_sm1_46_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_47 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_47_us_h2d),
    .tl_h_o       (tl_sm1_47_us_d2h),
    .tl_d_o       (tl_sm1_47_ds_h2d),
    .tl_d_i       (tl_sm1_47_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_48 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_48_us_h2d),
    .tl_h_o       (tl_sm1_48_us_d2h),
    .tl_d_o       (tl_sm1_48_ds_h2d),
    .tl_d_i       (tl_sm1_48_ds_d2h)
  );
  tlul_socket_1n #(
    .HReqPass  (1'b0),
    .HRspPass  (1'b0),
    .DReqDepth (80'h0),
    .DRspDepth (80'h0),
    .N         (20)
  ) u_s1n_49 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_49_us_h2d),
    .tl_h_o       (tl_s1n_49_us_d2h),
    .tl_d_o       (tl_s1n_49_ds_h2d),
    .tl_d_i       (tl_s1n_49_ds_d2h),
    .dev_select_i (dev_sel_s1n_49)
  );
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h4),
    .DReqDepth (64'h0),
    .DRspDepth (64'h0),
    .PreventOverwhelming (1'b1),
    .N         (16)
  ) u_s1n_50 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_50_us_h2d),
    .tl_h_o       (tl_s1n_50_us_d2h),
    .tl_d_o       (tl_s1n_50_ds_h2d),
    .tl_d_i       (tl_s1n_50_ds_d2h),
    .dev_select_i (dev_sel_s1n_50)
  );

endmodule
